board/urls.py
from django.urls import path
from board import views


app_name = 'board' # appname을 지정해주면 동일한 name속성에도 구분할 수 있다.

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:question_id>/', views.detail, name="detail"),
    # question Create Update Delete
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>', views.question_delete, name='question_delete'),
    # answer Create Update Delete
    path('answer/create/<int:answer_id>/', views.answer_create, name="answer_create"),
    # path('answer/modify/<int:answer_id>/', views.answer_modify, name="answer_modify"),
    # path('answer/delete/<int:answer_id>/', views.answer_delete, name="answer_delete"),
]

sinriboard/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('', views.index), # 임시 메인 화면
    path('admin/', admin.site.urls),  # login 쪽으로 가는 거 같음
    path('board/', include('board.urls')),
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path
from .views import index, signup
from django.contrib.auth import views as auth_view


app_name = 'user'

urlpatterns = [
    path('', index, name="index"),
    # path('login/', login, name="login"),
    path('login/', auth_view.LoginView.as_view(template_name="user/login.html"), name="login"), # contrib API에 이미 있는 로그인 창이 있다.
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name="signup")
]

# print(auth_view.LoginView.as_view)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, sinriboard!</title>
</head>
<body>

<header>
<!--navbar.html을 include-->
{% include 'navbar.html' %}
</header>

<!--개별 template 추가 영역 시작-->
<main>
{% block content %}
{% endblock %}
</main>

</body>
</html>

templates/navbar.html
<nav>
    <a href="{% url 'board:index' %}">sinriboard</a>
    <div class="toggle-nav">
        <ul>
            <li>
                {% if user.is_authenticated %}
                    <a href="{% url 'user:logout' %}">로그아웃</a>
                {% else %}
                    <a href="{% url 'user:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>