board/urls.py
from django.urls import path
from board import views


app_name = 'board' # appname을 지정해주면 동일한 name속성에도 구분할 수 있다.

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:question_id>/', views.detail, name="detail"),
    # question Create Update Delete
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>', views.question_delete, name='question_delete'),
    # answer Create Update Delete
    path('answer/create/<int:answer_id>/', views.answer_create, name="answer_create"),
    # path('answer/modify/<int:answer_id>/', views.answer_modify, name="answer_modify"),
    # path('answer/delete/<int:answer_id>/', views.answer_delete, name="answer_delete"),
]

sinriboard/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('', views.index), # 임시 메인 화면
    path('admin/', admin.site.urls),  # login 쪽으로 가는 거 같음
    path('board/', include('board.urls')),
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path
from .views import index, signup
from django.contrib.auth import views as auth_view


app_name = 'user'

urlpatterns = [
    path('', index, name="index"),
    # path('login/', login, name="login"),
    path('login/', auth_view.LoginView.as_view(template_name="user/login.html"), name="login"), # contrib API에 이미 있는 로그인 창이 있다.
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name="signup")
]

# print(auth_view.LoginView.as_view)

board/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Question(models.Model):
    # User모델을 ForeignKey로 적용,
    # on_delete= 삭제 조건. author이 삭제되면, Question 삭제
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # 수정을 한다면, 수정날짜를 데이터에 포함.
    modify_date = models.DateTimeField(null=True, blank=True)
    

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # on_delete= 모델 삭제 조건, question이 삭제되면 Answer 삭제
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    
    modify_date = models.DateTimeField(null=True, blank=True)

    

board/forms.py
from django import forms
from board.models import Question, Answer # model이랑 연결


class QuestionForm(forms.ModelForm): # froms.ModelForm을 상속했다.
    class Meta: # 필수 inner 클래스
        model = Question # 사용할 모델
        fields = ['subject', 'content'] # QuestionForm에서 사용할 Question 모델의 속성
        # 추가 설정 - tag와 class, 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'from-control', 'rows': 10})
        # }
        # 추가 설정  label
        labels = {
            'subject': '질문 제목',
            'content': '질문 내용'
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변 내용'
        }

board/views.py
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from itertools import islice
from math import ceil


# Create your views here.
def index(request):
    """
    board 목록 출력
    :param request:
    :return:
    """
    page = request.GET.get('page', '1')

    question_list = Question.objects.order_by('-create_date') # -가 붙어있으면 역방향이다.
    # question_list = get_object_or_404(Question).order_by('-create_date')
    question_count = question_list.count
    
    paginator = Paginator(question_list, 10) # 페이지당 10개 보여주기
    page_obj = paginator.get_page(page)
    
    context = {
        'question_list': page_obj,
        'question_count': question_count
    }
    return render(request, 'board/question_list.html', context)


def temp_pagination(question_count, question_list):
    # pagination
    total_page = ceil(question_count / 5)
    cur_page = 1
    cur_list = islice(question_list, (cur_page-1)*5 + 1, cur_page*5)


def detail(request, question_id):
    """
    baord 질문 내용 출력
    :param request:
    :param id:
    :return:
    """
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id) # 404 에러로 핸들링하기
    context = {
        'question': question
    }
    
    return render(request, 'board/question_detail.html', context)
    # return HttpResponse(f'board/{id} 페이지입니다.')


@login_required(login_url='user:login')
def answer_create(request, question_id):
    """
    board 질문의 답변 생성
    @login_required: answer model에 author는 auth.model의 User을 참조한다.
    
    :param request:
    :param question_id:
    :return:
    """
    question = get_object_or_404(Question, pk=question_id)
    
    # 1. answer_set 이용하기
    # question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    
    # 2. Answer class(model) 이용하기
    # answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    # answer.save()
    
    # 3. form API 이용하기
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = AnswerForm()
    
    context = {'question': question, 'form': form}
    return render(request, 'board/question_detail.html', context)


@login_required(login_url='user:login')
def question_create(request):
    """
    Question 질문 등록
    :param request:
    :param question_id:
    :return:
    """
    
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        # request.POST에는 form태그에서 작성한 속성과 값이 자동으로 저장되어 객체가 생성된다.

        if form.is_valid(): # form이 유효한지 확인한다.
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('board:index')
        
    else: # 초기에 a링크로 질문하기를 클릭하면 GET방식으로 페이지에 들어오기때문에
        # GET request를 대비한 코드를 작성해야한다.
        form = QuestionForm()
        
    context = {'form': form}
    
    return render(request, 'board/question_form.html', context)


@login_required(login_url='user:login')
def question_modify(request, question_id):
    """
    질문 수정하기
    :param request:
    :param question_id: Question model의 question_id
    :return: render
    """
    question = get_object_or_404(Question, pk=question_id)
    
    # user가 다를 때는 수정을 못하게 막는다.
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다!')
        return redirect('board:detail', question_id=question.id)
    
    if request.method == "POST":
        # instance= :지정시 form이 instance로 채워진다.
        # 즉, instance로 채우고 request.POST로 다시 덮어쓰는 것임
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('board:detail', question_id=question.id)
        
    else:
        form = QuestionForm()

    context = {
        'form': form,
        'question': question
    }
    
    return render(request, 'board/question_modify.html', context)


@login_required(login_url='user:login')
def question_delete(request, question_id):
    """
    질문 삭제하기
    :param request:
    :param question_id:
    :return:
    """
    question = get_object_or_404(Question, pk=question_id)
    
    # 작성자만 삭제 가능
    if request.user != question.author:
        print('삭제 권한 없음')
        messages.error(request, "삭제 권한이 없습니다.")
        return redirect('board:detail', question_id=question_id)
    
    # 삭제
    question.delete()
    
    return redirect('board:index')
    

@login_required(login_url='user:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    
    if request.user != answer.author:
        messages.error(request, '권한이 없습니다')
        return redirect('board:detail', question_id=answer.question.id)
    
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('board:detail', answer.question.id)
        
    else:
        form = AnswerForm()
   
    context = {
        'form': form,
        'answer': answer
    }
    
    # return redirect('board:detail', answer.question.id)
    # return render(request, 'board/question_detail.html', context)
    
    

@login_required(login_url='user:login')
def answer_delete(request, answer_id):
    
    
    return HttpResponse('답글 삭제페이지 입니다')
    

templates/board/answer_form.html
<div class="answer-list">
    <h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
    <ul>
        {% for answer in question.answer_set.all %}
            <li>
                {{ answer.content }}
                <span>{{ answer.create_date }}</span>
<!--                <a href="{% url 'board:answer_modify' answer.id %}">수정하기</a>-->
<!--                <a href="{% url 'board:answer_delete' answer.id %}">삭제하기</a>-->
            </li>

<!--        전부 rendering하는거는 비효율적임 다른 방법이 있을거임 -->
<!--            {% if form %}-->
<!--            <div> form? </div>-->
<!--            {% endif %}-->
<!--            <li>-->
<!--                <form method="post">-->
<!--                    -->
<!--                </form>-->
<!--            </li>-->
        {% endfor %}
    </ul>
</div>

templates/board/question_detail.html
{% extends 'base.html' %}
{% block content %}
<section>

<!-- 질문 글 -->
<div class="question-content">
    <span>{{ question.id }}{{ question.create_date }}</span>
    <h1>{{ question.subject }}</h1>
    <p>{{ question.content }}</p>

    <a href="{% url 'board:question_modify' question.id %}">수정하기</a>
    <span>마지막 수정일자: {{ question.modify_date }}</span>
    <a href="{% url 'board:index' %}">뒤로가기</a>
    <a href="{% url 'board:question_delete' question.id %}">삭제하기</a>
</div>

<!-- 경고창 -->
<div class="alert">
    {% if messages %}
    <div>
        <strong>권한이 없습니다.</strong>
        {% for message in messages %}
            <div>{{ message.tags }}</div>
            <div>{{ message.message }}</div>
        {% endfor %}
    </div>
    {% endif %}
</div>

<!-- 답변 글들 -->
{% include 'board/answer_form.html' %}

<!-- 답변 등록하기-->
<div class="answer-create">
    <form action="{% url 'board:answer_create' question.id %}" method="post">
        {% csrf_token %}

        {% if form.errors %}
        <div class="form-alert" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.errors }}</strong>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        <!-- devtool로 편집한다고해도 login페이지로 이동한다.-->
        <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" rows="15"></textarea>
        <input type="submit" value="답변등록" />

    </form>
</div>
</section>

{% endblock %}

templates/board/question_form.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h5>질문 등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- {{ form.as_p }}-->

        <!-- error handling -->
        {% if form.errors %}
        <div class="error-alert" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}은 필수 항목입니다</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        <div>
            <label for="subject">질문 제목</label>
            <input type="text" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}"/>
        </div>
        <div>
            <label for="content">질문 내용</label>
            <textarea type="text" name="content" id="content" rows="10" required></textarea>
        </div>

        <button type="submit">저장하기</button>
    </form>
</div>

{% endblock %}

templates/board/question_list.html
{% extends 'base.html' %}
{% block content %}
<div>

    {% if question_list %}
    <h5>{{ question_count }}개의 질문이 있습니다.</h5>
    <table>
    <thead>
        <tr>
            <th>번호</th>
            <th width="50%">질문 제목</th>
            <th>글쓴이</th>
            <th>일시</th>
        </tr>
    </thead>
    <tbody>
        {% for question in question_list %}
        <tr>
            <td><p>{{ question.id }}</p></td>
            <td><a href="{% url 'board:detail' question.id %}">
                {{ question.subject }}
                {% if question.answer_set.count > 0 %}
                    <strong>&#91;{{ question.answer_set.count }}&#93;</strong>
                {% endif %}
            </a></td>
            <td>{{ question.author }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
    </tbody>
    <!-- <li><a href="/board/{{question.id}}/">{{question.subject}}</a></li>-->
    </table>

    <!--pagination 시작하기-->
    <ul style="display: flex;">
    <!--이전 페이지-->
        {% if question_list.has_previous %}
            <li><a href="?page={{ question_list.previous_page_number }}">이전</a></li>
        {% else %}
            <li><a tabindex="-1" aria-disabled="true" href="#">이전</a></li>
        {% endif %}
    <!--페이지 리스트-->
        {% for page_number in question_list.paginator.page_range %}

            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                {% if page_number == question_list.number %}
                    <li class="btn-active" aria-current="page"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% else %}
                    <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% endif %}
            {% endif %}

        {% endfor %}
    <!--다음 페이지-->
        {% if question_list.has_next %}
            <li><a href="?page={{ question_list.next_page_number }}">다음</a></li>
        {% else %}
            <li><a tabindex="-1" aria-disabled="true" href="#"></a></li>
        {% endif %}`
    </ul>

    {% else %}
        <h5>질문이 없습니다.</h5>
    {% endif %}
</div>

<div>
    <a class="q-btn" href="{% url 'board:question_create' %}">질문하기</a>
</div>

{% endblock %}

templates/board/question_modify.html
{% extends 'base.html' %}
{% block content %}
<section>

<div>
    <h5>질문 등록</h5>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="subject">질문 제목</label>
            <input type="text" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:question.subject }}"
            />
        </div>
        <div>
            <label for="content">질문 내용</label>
            <textarea type="text" name="content" id="content" rows="10" required>
                {{question.content}}
            </textarea>
        </div>

        <button type="submit">저장하기</button>
    </form>
</div>
</section>
{% endblock %}