sinriboard/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('', views.index), # 임시 메인 화면
    path('admin/', admin.site.urls),  # login 쪽으로 가는 거 같음
    path('board/', include('board.urls')),
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path
from .views import index, signup
from django.contrib.auth import views as auth_view


app_name = 'user'

urlpatterns = [
    path('', index, name="index"),
    # path('login/', login, name="login"),
    path('login/', auth_view.LoginView.as_view(template_name="user/login.html"), name="login"), # contrib API에 이미 있는 로그인 창이 있다.
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name="signup")
]

# print(auth_view.LoginView.as_view)

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.core.exceptions import ValidationError


class UserForm(UserCreationForm):
    email = forms.EmailField(label="email")
    
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')
    

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserForm
from django.contrib.auth import authenticate, login


def index(request):
    return HttpResponse('hello user')


def signup(request):
    """
    회원가입, 계정생성 page
    :param request:
    :return:
    """
    if request.method == "POST":
        form = UserForm(request.POST) # 입력한 데이터로 사용자 생성
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            
            # authenticate 사용자 인증
            user = authenticate(username=username, password=raw_password)
            # login 로그인
            login(request, user)
            
            return redirect('board:index')
    
    else: # GET
        form = UserForm() # 계정 생성 화면 렌더링
    
    context = {'form': form}
    return render(request, 'user/signup.html', context)

templates/user/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div><strong>{{ filed.label }}</strong></div>
            {{ error }}
        {% endfor %}
    {% endfor %}

<!-- Non field Error: fieldError 와는 다른 이유로 에러가 발생한 경우-->
    {% for error in form.non_field_errors %}
        <div>something wrong! try again </div>
        {{ error }}
    {% endfor %}
{% endif %}

templates/user/login.html
{% extends 'base.html' %}
{% block content %}
<section class="component-login">
  <!--login 하기-->
  <form method="post" action="{% url 'user:login' %}">
    {% csrf_token %}
    <!-- ?next=/ 를 실행하기위한 코드 -->
    <input type="hidden" name="next" value="{{ next }}" />

    {% include 'user/form_errors.html' %}
    <div>
      <label for="username">ID</label>
      <input type="text" name="username" id="username"
             value="{{ form.username.value|default_if_none:'' }}"
      />
    </div>
    <div>
      <label for="password">PW</label>
      <input type="password" name="password" id="password"
             value="{{ form.password.value|default_if_none:'' }}"
      />
    </div>

    <button type="submit">로그인</button>
  </form>

  <!--회원 가입하기-->
  <div>
    <p>아직 계정이 없으세요? </p>
    <a href="{% url 'user:signup' %}">회원가입하기</a>
  </div>

</section>

{% endblock content %}

templates/user/signup.html
{% extends 'base.html' %}
{% block content %}

<section>
    <div>
        <h4>회원가입</h4>
<!--        <div>-->
<!--            <span><a href="{% url 'user:login' %}">로그인</a>하기</span>-->
<!--        </div>-->
    </div>

    <form method="post" action="{% url 'user:signup' %}">
        {% csrf_token %}
        {% include 'user/form_errors.html' %}

        <div>
            <label for="username">사용자 이름</label>
            <input type="text" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}"
            />
        </div>

        <div>
            <label for="password1">비밀번호</label>
            <input type="password" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}"
            />
        </div>

        <div>
            <label for="password2">비밀번호 확인</label>
            <input type="password" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}"
            />
        </div>

        <div>
            <label for="email">이메일</label>
            <input type="email" name="email" id="email"
                   value="{{ from.email.value|default_if_none:'' }}"
            />
        </div>

        <button type="submit">계정 생성</button>

    </form>

</section>

{% endblock %}